import { IData } from "../../hooks/types";

export const mockTagData: Array<IData> = [
  {
    synonyms: [
      "vanilla-javascript",
      "javascript-module",
      "vanilla-js",
      "vanillajs",
      "javascript-disabled",
      "javascript-alert",
      "javascript-dom",
      "javascript-library",
      "javascript-runtime",
      "classic-javascript",
      "ecmascript",
      "js",
      ".js",
      "javascript-execution",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 2528448,
    name: "javascript",
  },
  {
    synonyms: ["py", "pythonic", "python-interpreter", "python-shell"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 2191769,
    name: "python",
  },
  {
    synonyms: [
      "oraclejdk",
      "javax",
      "openjdk",
      "java-api",
      "java-se",
      ".java",
      "j2se",
      "core-java",
      "java-libraries",
      "jdk",
      "jre",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1917054,
    name: "java",
  },
  {
    synonyms: [
      "csharp",
      "c#-language",
      "c-sharp",
      "c#.net",
      "visual-c#",
      ".cs-file",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1614839,
    name: "c#",
  },
  {
    synonyms: [
      "php-namespaces",
      "php-include",
      "phtml",
      "phpinfo",
      "php-oop",
      "php-errors",
      "php-cli",
      "php.ini",
      "hypertext-preprocessor",
      "php-frameworks",
      "php5",
      "php-date",
      "php-fpm",
      "php-session",
      "php-mail",
      "php-functions",
      "php-cgi",
    ],
    collectives: [
      {
        tags: ["php"],
        external_links: [
          {
            type: "support",
            link: "https://stackoverflow.com/contact?topic=15",
          },
        ],
        description:
          "A collective where developers working with PHP can learn and connect about the open source scripting language.",
        link: "/collectives/php",
        name: "PHP",
        slug: "php",
      },
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1464322,
    name: "php",
  },
  {
    synonyms: [
      "android-framework",
      "android-application",
      "android-ui",
      "android-device",
      "android-mobile",
      "android-api",
      "android-sdk",
    ],
    collectives: [
      {
        tags: ["android", "ios"],
        external_links: [
          {
            type: "support",
            link: "https://stackoverflow.com/contact?topic=15",
          },
        ],
        description:
          "A collective for developers who want to share their knowledge and learn more about mobile development practices and platforms",
        link: "/collectives/mobile-dev",
        name: "Mobile Development",
        slug: "mobile-dev",
      },
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1416986,
    name: "android",
  },
  {
    synonyms: [
      "time-tag",
      "html5",
      "html-head",
      "html-syntax",
      "webpage",
      "div",
      "divs",
      "nested-divs",
      "div-layouts",
      "html-comments",
      "span",
      "html-attributes",
      "html-tag",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1187190,
    name: "html",
  },
  {
    synonyms: [
      "jquery-live",
      "jquery-core",
      "jquery-callback",
      "jquery-after",
      "jquery-get",
      "jquery-post",
      "jquery-hasclass",
      "toggleclass",
      "removeclass",
      "jquery-css",
      "jquery-find",
      "addclass",
      "jquery-filter",
      "jquery-effects",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1034769,
    name: "jquery",
  },
  {
    synonyms: ["cxx", "cpp"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 806652,
    name: "c++",
  },
  {
    synonyms: [
      "box-sizing",
      "css3",
      "css-text-shadow",
      "css-box-shadow",
      "css-border-radius",
      "css-border-image",
      "css-text-overflow",
      "box-shadow",
      "css-font-weight",
      "css-borders",
      "dynamic-css",
      "css-reset",
      "cascading-style-sheet",
      "css-layout",
      "css-attributes",
      "css-background-image",
      "css-validation",
      "box-model",
      "style.css-template-file",
      "css-display",
      "min-height",
      "min-width",
      "max-height",
      "max-width",
      "css-centering",
      "css-overflow",
      "css-line-height",
      "css-box-model",
      "font-weight",
      "alternate-stylesheets",
      "inline-block",
      "css-menu",
      "css-classes",
      "css-height",
      "css-inheritance",
      "css2",
      "css-columns",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 804114,
    name: "css",
  },
  {
    synonyms: ["iphone-os", "apple-ios", "ios-sdk"],
    collectives: [
      {
        tags: ["android", "ios"],
        external_links: [
          {
            type: "support",
            link: "https://stackoverflow.com/contact?topic=15",
          },
        ],
        description:
          "A collective for developers who want to share their knowledge and learn more about mobile development practices and platforms",
        link: "/collectives/mobile-dev",
        name: "Mobile Development",
        slug: "mobile-dev",
      },
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 687166,
    name: "ios",
  },
  {
    synonyms: [
      "select-statement",
      "sqlselect",
      "sql-select",
      "sql-syntax",
      "sql-query",
      "sql-statement",
      "sql-and",
      "sql-or",
      "sql-standards",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 670701,
    name: "sql",
  },
  {
    synonyms: [
      "mysql-query",
      "my-sql",
      "mysqld",
      "mysqlclient",
      "mysql-server",
      "mysql-table",
      "mysql-if",
      "mysqlsh",
      "mysqldump",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 661971,
    name: "mysql",
  },
  {
    synonyms: ["rstats", "r-language", "base-r"],
    collectives: [
      {
        tags: [
          "shiny",
          "rstudio",
          "r-caret",
          "r-raster",
          "r",
          "rvest",
          "data.table",
          "lubridate",
          "quantmod",
          "purrr",
          "shiny-server",
          "knitr",
          "r-package",
          "shinyapps",
          "forcats",
          "shinydashboard",
          "tidyr",
          "plyr",
          "tibble",
          "tidyverse",
          "readr",
          "dtplyr",
          "stringr",
          "ggplot2",
          "zoo",
          "dplyr",
          "rlang",
        ],
        external_links: [
          {
            type: "support",
            link: "https://stackoverflow.com/contact?topic=15",
          },
        ],
        description:
          "A collective where data scientists and AI researchers gather to find, share, and learn about R and other subtags like knitr and dplyr.",
        link: "/collectives/r-language",
        name: "R Language",
        slug: "r-language",
      },
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 505510,
    name: "r",
  },
  {
    synonyms: ["react-component", "react.js", "react", "react-jsx"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 476430,
    name: "reactjs",
  },
  {
    synonyms: ["nodejs", "io.js"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 471880,
    name: "node.js",
  },
  {
    synonyms: [
      "bytearray",
      "static-array",
      "swift-array",
      "arraycopy",
      "javascript-array",
      "sub-arrays",
      "character-arrays",
      "char-array",
      "jsonarray",
      "string-array",
      "mongodb-arrays",
      "array-of-objects",
      "array",
      "chararray",
      "array-of-dict",
      "arrayofstring",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 416674,
    name: "arrays",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 403904,
    name: "c",
  },
  {
    synonyms: ["asp.net-website", "aspx", "asp-net", "aspdotnet"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 374585,
    name: "asp.net",
  },
  {
    synonyms: ["json-parsing", "json-encode", "json-decode", "jsonobject"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 360297,
    name: "json",
  },
  {
    synonyms: ["py3", "python-3", "py3k", "python3k", "python3"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 343566,
    name: "python-3.x",
  },
  {
    synonyms: ["ror", "rails"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 338040,
    name: "ruby-on-rails",
  },
  {
    synonyms: ["dot-net", "dotnet", ".net-framework"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 337831,
    name: ".net",
  },
  {
    synonyms: ["ms-sql-server", "mssql", "sql-srever"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 334493,
    name: "sql-server",
  },
  {
    synonyms: ["swift1.2", "swift-ios", "swift-language"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 333345,
    name: "swift",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 311751,
    name: "django",
  },
  {
    synonyms: ["angularjs2", "angular2", "angular4", "angular4.x"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 304031,
    name: "angular",
  },
  {
    synonyms: ["objc"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 292321,
    name: "objective-c",
  },
  {
    synonyms: ["pandas-1.x", "pandas-2.x"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 286600,
    name: "pandas",
  },
  {
    synonyms: ["workbook", "excel-macro", "ms-excel"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 286431,
    name: "excel",
  },
  {
    synonyms: ["angular.js", "angular1.x"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 262748,
    name: "angularjs",
  },
  {
    synonyms: [
      "regexes",
      "regexp",
      "regular-expression",
      "regular-expressions",
      "regex-php",
      "perlre",
      "perl-regex",
      "apache-regexp",
      "regularexpression",
      "sql-regex",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 260222,
    name: "regex",
  },
  {
    synonyms: ["atscript", "vanilla-typescript"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 229616,
    name: "typescript",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 229035,
    name: "ruby",
  },
  {
    synonyms: ["linux-development"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 227439,
    name: "linux",
  },
  {
    synonyms: ["ajax-request", ".ajax"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 222010,
    name: "ajax",
  },
  {
    synonyms: [
      "iphone-sdk",
      "iphone-development",
      "iphone-app",
      "iphone-programming",
      "iphone-web",
      "iphone-ios",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 220714,
    name: "iphone",
  },
  {
    synonyms: ["xml-file"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 214646,
    name: "xml",
  },
  {
    synonyms: ["visual-basic-applications", "vba-macros", "macros-vba"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 214007,
    name: "vba",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 211349,
    name: "laravel",
  },
  {
    synonyms: ["spring-framework", "spring-java-config", "spring-config"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 211015,
    name: "spring",
  },
  {
    synonyms: [
      "aspnet-mvc",
      "aspnet.mvc",
      "asp.net.mvc",
      "asp-mvc",
      "asp-net-mvc",
      "asp.mvc",
      "mvc.net",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 201238,
    name: "asp.net-mvc",
  },
  {
    synonyms: ["databases", "db", "database-structure", "dbms"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 195090,
    name: "database",
  },
  {
    synonyms: [
      "wordpress-upgrade",
      "wordpress-plugin-dev",
      "wordpress-filter",
      "wordpress-widget",
      "wp-query",
      "wordpress-mu",
      "wordpress-theme-customize",
      "wordpress-plugin",
      "wpdb",
      "wordpress-loop",
      "wordpress-permission",
      "wordpress-admin",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 192278,
    name: "wordpress",
  },
  {
    synonyms: ["string-manipulation", "str", "strings", "empty-string"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 184426,
    name: "string",
  },
  {
    synonyms: [
      "flutter-sdk",
      "flutter-android",
      "flutter-ios",
      "flutter-desktop",
      "flutter-web",
      "flutter-test",
      "flutter-widget",
      "flutter-layout",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 176146,
    name: "flutter",
  },
  {
    synonyms: ["mongo", "mongod"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 175881,
    name: "mongodb",
  },
  {
    synonyms: ["pgsql", "postgres", "sql-postgres"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 175823,
    name: "postgresql",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 169611,
    name: "wpf",
  },
  {
    synonyms: [
      "windows-programming",
      "windows-application",
      "windows-applications",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 168671,
    name: "windows",
  },
  {
    synonyms: ["xcode-ide"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 159618,
    name: "xcode",
  },
  {
    synonyms: ["aws"],
    collectives: [
      {
        tags: [
          "aws-ssm",
          "aws-lambda",
          "amazon-fsx",
          "amazon-workspaces",
          "aws-sdk-js-v3",
          "amazon-personalize",
          "amazon-qldb",
          "aws-iot-events",
          "aws-datasync",
          "amazon-iam",
          "amazon-transcribe",
          "amazon-vpc",
          "amazon-ses",
          "aws-msk",
          "aws-fis",
          "aws-data-exchange",
          "amazon-ec2-spot-market",
          "aws-storage-gateway",
          "aws-appstream",
          "aws-codeguru",
          "aws-config",
          "aws-deeplens",
          "amazon-opensearch",
          "amazon-elasticache",
          "aws-documentdb",
          "aws-copilot",
          "aws-appsync",
          "aws-sdk-java",
          "aws-fargate",
          "aws-application-load-balancer",
          "amazon-inspector",
          "amazon-elasticsearch",
          "aws-api-gateway",
          "aws-iot-greengrass",
          "aws-sdk-net",
          "aws-codecatalyst",
          "aws-iot-sitewise",
          "aws-sdk-ruby",
          "aws-amplify",
          "aws-sdk-rust",
          "amazon-redshift-spectrum",
          "amazon-s3-select",
          "aws-media-convert",
          "aws-pinpoint",
          "amazon-gamelift",
          "amazon-guardduty",
          "aws-step-functions",
          "amazon-dynamodb",
          "amazon-rekognition",
          "alexa-sdk-python",
          "aws-dms",
          "amazon-lightsail",
          "aws-auto-scaling",
          "aws-codepipeline",
          "aws-sso",
          "aws-global-accelerator",
          "aws-xray",
          "aws-lambda-powertools",
          "amazon-comprehend",
          "aws-mediatailor",
          "aws-iam-identity-center",
          "aws-cloud9",
          "aws-sdk-android",
          "aws-secrets-manager",
          "amazon-data-pipeline",
          "aws-vpn",
          "aws-backup",
          "aws-sdk-nodejs",
          "aws-codecommit",
          "aws-sdk-js",
          "aws-resource-group",
          "amazon-cloudsearch",
          "aws-private-link",
          "amazon-cloudtrail",
          "amazon-appflow",
          "aws-elastictranscoder",
          "aws-mediaconnect",
          "aws-cli",
          "amazon-aurora",
          "amazon-bedrock",
          "amazon-location-service",
          "alexa-smapi",
          "amazon-workdocs",
          "aws-media-live",
          "amazon-elastic-transcoder",
          "aws-iot",
          "amazon-sumerian",
          "aws-security-hub",
          "amazon-quicksight",
          "amazon-memory-db",
          "aws-directory-services",
          "aws-chatbot",
          "amazon-kms",
          "amazon-managed-blockchain",
          "aws-certificate-manager",
          "aws-cdk",
          "elastic-ip",
          "amazon-ec2",
          "aws-sdk-comprehend",
          "amazon-textract",
          "amazon-eks",
          "amazon-ivs",
          "aws-reserved-instances",
          "amazon-kinesis-video-streams",
          "aws-service-catalog",
          "amazon-elastic-beanstalk",
          "amazon-s3",
          "amazon-sns",
          "amazon-neptune",
          "aws-transfer-family",
          "aws-iot-core",
          "amazon-sqs",
          "aws-codestar",
          "alexa-presentation-language",
          "amazon-athena",
          "aws-billing",
          "amazon-lex",
          "amazon-cloudwatchlogs",
          "aws-codebuild",
          "aws-control-tower",
          "aws-snowball",
          "aws-glue",
          "amazon-cloudhsm",
          "aws-serverless",
          "amazon-glacier",
          "amazon-forecast",
          "amazon-simpledb",
          "aws-elemental",
          "amazon-cloudwatch",
          "amazon-ami",
          "amazon-macie",
          "alexa-interaction-model",
          "amazon-sagemaker",
          "amazon-app-runner",
          "amazon-emr",
          "aws-graviton",
          "amazon-dynamodb-dax",
          "amazon-kendra",
          "aws-sdk",
          "amazon-route53",
          "amazon-honeycode",
          "aws-mediapackage",
          "aws-direct-connect",
          "aws-event-bridge",
          "alexa-sdk-nodejs",
          "aws-lake-formation",
          "amazon-translate",
          "amazon-kinesis",
          "amazon-ecs",
          "aws-acm",
          "aws-sdk-go-v2",
          "amazon-connect",
          "aws-organizations",
          "aws-cloudmap",
          "amazon-sagemaker-compilers",
          "aws-databrew",
          "amazon-timestream",
          "aws-copilot-cli",
          "alexa-smart-home-skill",
          "aws-sdk-java-2.0",
          "amazon-waf",
          "amazon-polly",
          "aws-iot-analytics",
          "amazon-cloudfront",
          "amazon-imagebuilder",
          "aws-sam",
          "aws-sdk-mock",
          "aws-security-group",
          "aws-elb",
          "aws-cloudshell",
          "amazon-elb",
          "aws-codeartifact",
          "aws-device-farm",
          "amazon-workmail",
          "aws-sdk-go",
          "aws-nlb",
          "aws-mediastore",
          "aws-sct",
          "amazon-ebs",
          "aws-sdk-ios",
          "aws-app-mesh",
          "amazon-mq",
          "aws-lambda-edge",
          "amazon-ecr",
          "amazon-redshift",
          "alexa-skills-kit",
          "alexa-flash-briefing-skill",
          "aws-sdk-cpp",
          "aws-parameter-store",
          "amazon-kinesis-analytics",
          "amazon-keyspaces",
          "alexa-account-linking",
          "amazon-swf",
          "aws-batch",
          "aws-opsworks",
          "aws-app-config",
          "aws-code-deploy",
          "amazon-efs",
          "amazon-rds",
          "amazon-kinesis-firehose",
          "aws-mobilehub",
          "aws-cloudformation",
          "aws-sam-cli",
          "amazon-web-services",
          "amazon-cognito",
        ],
        external_links: [
          {
            type: "website",
            link: "https://aws.amazon.com",
          },
          {
            type: "support",
            link: "mailto:awscollective@amazon.com",
          },
          {
            type: "twitter",
            link: "https://twitter.com/awsdevelopers",
          },
          {
            type: "github",
            link: "https://github.com/aws",
          },
          {
            type: "facebook",
            link: "https://facebook.com/amazonwebservices",
          },
          {
            type: "instagram",
            link: "https://instagram.com/amazonwebservices",
          },
        ],
        description:
          "Amazon Web Services (AWS) is the world’s most comprehensive and broadly adopted cloud platform, offering over 200 fully featured services from data centers globally. The AWS Collective is a community-driven site with resources for  developers.",
        link: "/collectives/aws",
        name: "AWS",
        slug: "aws",
      },
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 158343,
    name: "amazon-web-services",
  },
  {
    synonyms: [
      ".bash-profile",
      "bash-function",
      "bash-script",
      "bashrc",
      ".bashrc",
      "bash-alias",
      "bash-variables",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 155623,
    name: "bash",
  },
  {
    synonyms: ["git-commands"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 152174,
    name: "git",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 151485,
    name: "oracle",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 147938,
    name: "spring-boot",
  },
  {
    synonyms: [
      "data.frame",
      "dataframes",
      "pandas-df",
      "r-df",
      "df",
      "data-frame",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 145926,
    name: "dataframe",
  },
  {
    synonyms: ["firebase-android"],
    collectives: [
      {
        tags: [
          "firebase-performance",
          "google-cloud-pubsublite",
          "google-cloud-instance-template",
          "google-cloud-transcoder",
          "google-container-os",
          "google-cloud-monitoring",
          "google-cloud-automl",
          "firebase-polymer",
          "dialogflow-es-fulfillment",
          "google-cloud-language",
          "google-prediction",
          "google-cloud-stackdriver",
          "google-cloud-asset-inventory",
          "google-cloud-error-reporting",
          "google-cloud-dataproc-metastore",
          "google-cloud-source-repos",
          "firebase-crash-reporting",
          "google-cloud-memorystore",
          "google-cloud-profiler",
          "google-fusion-tables",
          "google-cloud-translate",
          "apigee",
          "google-container-registry",
          "google-cloud-build",
          "google-cloud-router",
          "google-cloud-internal-load-balancer",
          "firebase-app-distribution",
          "rest-firebase",
          "firebase",
          "google-cloud-dataprep",
          "google-app-engine-patch",
          "google-cloud-datalab",
          "firebase-in-app-messaging",
          "firebase-ab-testing",
          "firebase-security",
          "nativescript-firebase",
          "google-cloud-vision",
          "google-cloud-iot",
          "bigtable",
          "google-cloud-code",
          "google-cloud-storage-r",
          "google-cloud-print",
          "dialogflow-es",
          "cloud-document-ai",
          "google-cloud-powershell",
          "firebase-job-dispatcher",
          "google-cloud-sql",
          "firebase-database",
          "firebase-admin",
          "firebase-console",
          "google-cloud-dlp",
          "google-app-engine",
          "google-cloud-php-client",
          "google-cloud-data-fusion",
          "google-cloud-interconnect",
          "firebase-analytics",
          "firebase-admob",
          "google-cloud-speech",
          "looker-studio",
          "google-cloud-url-maps",
          "google-cloud-dataproc",
          "google-cloud-debugger",
          "google-cloud-networking",
          "google-app-engine-python",
          "firebase-mlkit",
          "google-cloud-cpp",
          "google-cloud-ai-platform-pipelines",
          "google-cloud-iam",
          "google-cloud-repository",
          "firebase-app-indexing",
          "google-cloud-launcher",
          "looker",
          "google-cloud-kms",
          "google-translate",
          "google-container-optimized-os",
          "google-cloud-scheduler",
          "google-cloud-dataflow",
          "google-cloud-webrisk",
          "apigee-baas",
          "google-cloud-console",
          "google-container-builder",
          "google-cloud-deploy",
          "firebase-app-check",
          "google-cloud-platform",
          "google-cloud-composer",
          "stackdriver",
          "google-bigquery",
          "google-cloud-vertex-ai",
          "google-cloud-spanner-emulator",
          "google-cloud-talent-solution",
          "firebase-realtime-database",
          "google-cloud-identity",
          "dialogflow-cx",
          "firebase-cli",
          "google-cloud-data-transfer",
          "redux-saga-firebase",
          "google-cloud-storage",
          "firebaseui",
          "google-cloud-run",
          "firebase-predictions",
          "google-cloud-tasks",
          "google-cloud-search",
          "google-cloud-functions",
          "google-cloud-ml-engine",
          "google-app-engine-php",
          "google-cloud-vpn",
          "firebase-authentication",
          "firebasesimplelogin",
          "google-cloud-load-balancer",
          "jib",
          "google-cloud-resource-manager",
          "google-cloud-shell-editor",
          "google-anthos",
          "google-cloud-healthcare",
          "google-analytics-firebase",
          "google-cloud-intellij",
          "firebase-remote-config",
          "firebase-machine-learning",
          "google-cloud-filestore",
          "react-native-firebase",
          "google-cloud-endpoints",
          "firebase-extensions",
          "firebase-notifications",
          "google-cloud-tools",
          "firebase-cloud-messaging",
          "google-cloud-sdk",
          "google-cloud-instances",
          "google-cloud-logging",
          "firebase-queue",
          "google-cloud-identity-aware-proxy",
          "google-cloud-firestore",
          "google-cloud-ai",
          "vertex-ai-search",
          "google-cloud-tpu",
          "google-app-engine-go",
          "firebase-test-lab",
          "google-dataflow",
          "google-cloud-test-lab",
          "google-cloud-dns",
          "google-cloud-shell",
          "google-cloud-registry",
          "google-cloud-marketplace",
          "google-cloud-proxy",
          "google-cloud-api-gateway",
          "firebase-util",
          "google-migrate-for-compute-engine",
          "gcloud",
          "google-cloud-node",
          "google-cloud-python",
          "google-cloud-ml",
          "firebase-assistant",
          "google-cloud-metrics",
          "google-cloud-save",
          "google-cloud-network-load-balancer",
          "google-cloud-robotics",
          "maven-jib",
          "firebase-tools",
          "cordova-plugin-firebasex",
          "google-app-engine-golang",
          "google-cloud-workstations",
          "firebase-invites",
          "google-cloud-recommendation",
          "google-cloud-datastore",
          "google-cloud-bigtable",
          "google-cloud-automl-nl",
          "google-cloud-endpoints-v2",
          "google-cloud-visualstudio",
          "google-cloud-pubsub",
          "google-cloud-cdn",
          "google-cloud-messaging",
          "google-cloud-billing",
          "recaptcha-enterprise",
          "firebase-hosting",
          "google-cloud-spanner",
          "google-cloud-armor",
          "google-kubernetes-engine",
          "react-redux-firebase",
          "google-cloud-trace",
          "firebase-storage",
          "google-cloud-http-load-balancer",
          "google-compute-engine",
          "google-cloud-print-privet",
          "firebase-dynamic-links",
          "google-cloud-ops-agent",
          "google-cloud-nl",
          "google-app-engine-deploy",
          "google-app-engine-launch",
        ],
        external_links: [
          {
            type: "support",
            link: "https://stackoverflow.com/contact?topic=15",
          },
        ],
        description:
          "A collective for developers who utilize Google Cloud’s infrastructure and platform capabilities. This collective is organized and managed by the Stack Overflow community.",
        link: "/collectives/google-cloud",
        name: "Google Cloud",
        slug: "google-cloud",
      },
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 143224,
    name: "firebase",
  },
  {
    synonyms: [
      "lists",
      "ilist",
      "python-list",
      "list-comparison",
      "generic-list",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 141556,
    name: "list",
  },
  {
    synonyms: ["vb", "vbproj"],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 140258,
    name: "vb.net",
  },
  {
    synonyms: [
      "cross-threading",
      "multi-threaded",
      "threads",
      "thread",
      "threading",
      "multithread",
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 140231,
    name: "multithreading",
  },
];
